- id: "/"
  title: "Conferenza Italiana Studenti di Fisica 2018"
  description: "La CISF costituisce il principale evento annuale organizzato dall'Associazione Italiana Studenti di Fisica (AISF).
Giunta alla sua IV edizione, la CISF 2018 si svolgerà a Pisa, dove circa 150 studenti
provenienti da tutta Italia avranno la possibilità di visitare i maggiori centri di ricerca e laboratori
della zona, ascoltare interventi di illustri professori e ricercatori. Non per ultimo conoscere e vivere la quotidianità dell'ambiente universitario pisano,
reso unico dalla compresenza dell'Università di Pisa, Scuola Normale Superiore, Scuola Superiore Sant'Anna, INFN e CNR."
  keywords: "CISF conferenza aisf associazione italiana studenti di fisica pisa visita virgo cnr infn smart nest"
