- id: "/"
  title: "CISF18 - Quarta Conferenza Italiana Studenti di Fisica"
  description: "La Quarta Conferenza Italiana Studenti di Fisica si svolgerà a Pisa dal 19 al 23 aprile 2018 e permetterà a circa 150 studenti provenienti da tutta Italia di condividere un'esperienza ricca e dal lato scientifico e da quello sociale nell'evento nazionale più importante dell'Associazione Italiana Studenti di Fisica"
  keywords: "aisf associazione italiana studenti di fisica iaps universita italia "
